Remove pin cpp_std to gnu++17
Previous error was:

  error: initialization of non-aggregate type 'struct ManagedDrmGem'
  with a designated initializer list

which, IIUC, was because of the `delete`-ed copy constructor. Switch
to not doing initializer list init.

Bug: 311052584
Test: set `cpp_std: "gnu++20"`
Test: cvd hardware/google/gfxstream/guest && mma
Change-Id: I5b6b0e023460859943bd632fc56973888a0205ea