Revert "Fix vk_append_struct to add elements after the last one"
This reverts commit 589c957ec9924f86757067b9195480fc95b3877a.

Reason for revert: Emulator build break:

I0425 08:32:25.637401 139856603629312 process.py:43] In file included from /usr/local/google/home/lfy/emu/device/generic/goldfish-opengl/system/vulkan_enc/AndroidHardwareBuffer.cpp:19:
I0425 08:32:25.637607 139856603629312 process.py:43] /usr/local/google/home/lfy/emu/device/generic/goldfish-opengl/system/vulkan_enc/vk_util.h:229:7: error: no member named 'abort' in the global namespace
I0425 08:32:25.637734 139856603629312 process.py:43]     ::abort();  // crash on loops in the chain
I0425 08:32:25.637989 139856603629312 process.py:43]     ~~^
I0425 08:32:25.638082 139856603629312 process.py:43] 1 error generated.

Change-Id: I61bc2011e51bc92a3fffcb36910d916092d3897d