Revert "Create a buffer independent cb_handle_t base class"
This reverts commit 1c1504300cb26896287058103327099c7c5771d3.

Reason for revert: error: 'nullptr' was not declared in this scope

Change-Id: I8cfbaf9182f6d15f8d2d2560f47360f43ceb47ac